package sakila::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'sakila::Schema',
    
    connect_info => {
        dsn => sakila->config->{dsn},
        user => 'on_connect_do=PRAGMA foreign_keys = ON',
        password => '',
    }
);

=head1 NAME

sakila::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<sakila>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<sakila::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Jeff T

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
